version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: cvwebsite-api
    volumes:
      - .:/app
  client:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: cvwebsite-client
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
