services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: cv-website-api
  client:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: cv-website-client
    ports:
      - "3000:80"
