version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    image: cvwebsite-api
    volumes:
      - ./backend/app:/app/api/app
  client:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    image: cvwebsite-client
    volumes:
      - ./frontend:/app/client/app
      - ./frontend/node_modules:/app/client/node_modules
    ports:
      - "8080:8080"
